server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smallShop
    username: root
    password: #?? DB ????
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: false
        format_sql: true


